CATEGORIES = [
    {
        "id": "indonesia_nickel",
        "name": "印尼镍矿 RKAB 配额",
        "icon": "🏭",
        "color": "#ef4444",
        "priority": 1,
        "description": "最大政策变量：印尼2026年RKAB配额从3.8亿吨砍至2.5亿吨，华飞12万吨项目年底投产",
        "keywords": [
            "印尼 RKAB 镍矿配额",
            "华友钴业 印尼 镍",
            "印尼镍矿 政策",
            "华飞 湿法 镍",
            "Indonesia nickel quota RKAB",
        ],
        "watch_points": [
            "RKAB 实际下发进度（每季度）",
            "华飞12万吨湿法项目投产节奏",
            "印尼钴副产品特许权使用费政策",
            "镍矿石成本端变化",
        ],
    },
    {
        "id": "lithium",
        "name": "锂业务兑现",
        "icon": "🔋",
        "color": "#8b5cf6",
        "priority": 2,
        "description": "利润引擎切换：2026年锂业务预计贡献40-60亿利润，津巴布韦Arcadia锂矿+5万吨硫酸锂厂",
        "keywords": [
            "华友钴业 锂",
            "津巴布韦 锂矿 出口",
            "华友 硫酸锂",
            "Arcadia 锂矿",
            "碳酸锂 价格",
        ],
        "watch_points": [
            "津巴布韦锂精矿出口批文落地",
            "硫酸锂厂产能爬坡进度",
            "碳酸锂/氢氧化锂现货价走势",
            "华友锂产品单吨成本",
        ],
    },
    {
        "id": "cashflow",
        "name": "资本开支与现金流",
        "icon": "💰",
        "color": "#f59e0b",
        "priority": 3,
        "description": "多线扩张期：2026Q1投资现金流净流出同比扩大27%，关注经营现金流能否覆盖资本开支",
        "keywords": [
            "华友钴业 现金流",
            "华友钴业 定增 融资",
            "华友钴业 资本开支",
            "华友钴业 资产负债率",
            "华友钴业 季报 业绩",
        ],
        "watch_points": [
            "季度经营现金流 vs 资本开支",
            "资产负债率趋势",
            "再融资计划（定增/可转债）",
            "在建工程转固节奏",
        ],
    },
    {
        "id": "europe_cathode",
        "name": "欧洲正极材料",
        "icon": "🇪🇺",
        "color": "#3b82f6",
        "priority": 4,
        "description": "匈牙利一期2.5万吨正极材料产线调试中，签约LGES和亿纬锂能长单",
        "keywords": [
            "华友钴业 匈牙利",
            "华友 正极材料 欧洲",
            "华友 LGES 长单",
            "亿纬锂能 华友 超高镍",
            "欧洲 正极材料 本土化",
        ],
        "watch_points": [
            "匈牙利项目正式量产出货时间",
            "欧洲IRA/CBAM法规动态",
            "LGES/亿纬长单量价条款",
            "正极材料加工费趋势",
        ],
    },
    {
        "id": "cobalt_copper",
        "name": "钴铜价格与供给",
        "icon": "⛏️",
        "color": "#10b981",
        "priority": 5,
        "description": "钴是华友的老本行，铜是印尼湿法的重要副产品，刚果金供给扰动需关注",
        "keywords": [
            "钴价 走势",
            "铜价 走势",
            "刚果金 钴矿",
            "华友钴业 钴 铜",
            "cobalt price DRC",
        ],
        "watch_points": [
            "钴价走势（刚果金供给端）",
            "铜副产品对镍项目利润贡献",
            "固态电池等新路线对钴需求的影响",
        ],
    },
]
